name: Run specs on supported Solidus versions

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  run-specs-with-postgres:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13
        ports: [5432:5432]
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
    env:
      DB: postgresql
      RAILS_ENV: test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3.8
      - name: Install dependencies
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3
      - name: Overwrite dummy database.yml for CI
        run: |
          mkdir -p spec/dummy/config
          cat <<'EOF' > spec/dummy/config/database.yml
          default: &default
            adapter: <%= ENV['DB'] == 'mysql' ? 'mysql2' : ENV['DB'] == 'postgresql' ? 'postgresql' : 'sqlite3' %>
            encoding: utf8
            pool: 5
            username: <%= ENV['DB'] == 'mysql' ? 'root' : ENV['DB'] == 'postgresql' ? 'postgres' : '' %>
            password: <%= ENV['DB'] == 'mysql' ? 'root' : ENV['DB'] == 'postgresql' ? 'postgres' : '' %>
            host: <%= ENV['DB'] == 'mysql' || ENV['DB'] == 'postgresql' ? '127.0.0.1' : '' %>
            port: <%= ENV['DB'] == 'mysql' ? 3306 : ENV['DB'] == 'postgresql' ? 5432 : '' %>

          development:
            <<: *default
            database: <%= ENV['DB'] == 'mysql' ? 'solidus_development' : ENV['DB'] == 'postgresql' ? 'solidus_development' : 'db/solidus_development.sqlite3' %>

          test:
            <<: *default
            database: <%= ENV['DB'] == 'mysql' ? 'solidus_test' : ENV['DB'] == 'postgresql' ? 'solidus_test' : 'db/solidus_test.sqlite3' %>

          production:
            <<: *default
            database: <%= ENV['DB'] == 'mysql' ? 'solidus_production' : ENV['DB'] == 'postgresql' ? 'solidus_production' : 'db/solidus_production.sqlite3' %>
          EOF
      - name: Build dummy app
        run: bundle exec rake test_app
      - name: Run tests
        run: bundle exec rake

  run-specs-with-mysql:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8
        ports: [3306:3306]
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: solidus_test
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
    env:
      DB: mysql
      RAILS_ENV: test
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: solidus_test
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3.8
      - name: Install dependencies
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3
      - name: Overwrite dummy database.yml for CI
        run: |
          mkdir -p spec/dummy/config
          cat <<'EOF' > spec/dummy/config/database.yml
          default: &default
            adapter: <%= ENV['DB'] == 'mysql' ? 'mysql2' : ENV['DB'] == 'postgresql' ? 'postgresql' : 'sqlite3' %>
            encoding: utf8
            pool: 5
            username: <%= ENV['DB'] == 'mysql' ? 'root' : ENV['DB'] == 'postgresql' ? 'postgres' : '' %>
            password: <%= ENV['DB'] == 'mysql' ? 'root' : ENV['DB'] == 'postgresql' ? 'postgres' : '' %>
            host: <%= ENV['DB'] == 'mysql' || ENV['DB'] == 'postgresql' ? '127.0.0.1' : '' %>
            port: <%= ENV['DB'] == 'mysql' ? 3306 : ENV['DB'] == 'postgresql' ? 5432 : '' %>

          development:
            <<: *default
            database: <%= ENV['DB'] == 'mysql' ? 'solidus_development' : ENV['DB'] == 'postgresql' ? 'solidus_development' : 'db/solidus_development.sqlite3' %>

          test:
            <<: *default
            database: <%= ENV['DB'] == 'mysql' ? 'solidus_test' : ENV['DB'] == 'postgresql' ? 'solidus_test' : 'db/solidus_test.sqlite3' %>

          production:
            <<: *default
            database: <%= ENV['DB'] == 'mysql' ? 'solidus_production' : ENV['DB'] == 'postgresql' ? 'solidus_production' : 'db/solidus_production.sqlite3' %>
          EOF
      - name: Build dummy app
        run: bundle exec rake test_app
      - name: Run tests
        run: bundle exec rake