name: Run specs on supported Solidus versions

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  run-specs-with-postgres:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13
        ports: [5432:5432]
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
    env:
      DB: postgres
      RAILS_ENV: test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3.8
      - name: Install dependencies
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3
      - name: Run tests
        run: bundle exec rake

  run-specs-with-mysql:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8
        ports: [3306:3306]
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: solidus_test
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
    env:
      DB: mysql
      RAILS_ENV: test
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: solidus_test
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3.8
      - name: Install dependencies
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3
      - name: Run tests
        run: bundle exec rake