name: Run specs on supported Solidus versions

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  run-specs-with-postgres:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13
        ports: [5432:5432]
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
    env:
      DB: postgresql
      RAILS_ENV: test
      DB_ADAPTER: postgresql
      DB_HOST: 127.0.0.1
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3.8
      - name: Cache Ruby gems
        uses: actions/cache@v4
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: Install dependencies
        run: |
          gem install bundler
          bundle config set --local path vendor/bundle
          bundle install --jobs 4 --retry 3
      - name: Create database configuration
        run: |
          mkdir -p spec/dummy/config
          cat > spec/dummy/config/database.yml << EOF
          default: &default
            adapter: ${DB_ADAPTER}
            encoding: utf8
            pool: 5
            username: ${DB_USERNAME}
            password: ${DB_PASSWORD}
            host: ${DB_HOST}
            port: ${DB_PORT}

          development:
            <<: *default
            database: solidus_development

          test:
            <<: *default
            database: solidus_test

          production:
            <<: *default
            database: solidus_production
          EOF
      - name: Build dummy app
        run: bundle exec rake extension:test_app
      - name: Run tests
        run: bundle exec rake

  run-specs-with-mysql:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8
        ports: [3306:3306]
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: solidus_test
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
    env:
      DB: mysql
      RAILS_ENV: test
      DB_ADAPTER: mysql2
      DB_HOST: 127.0.0.1
      DB_PORT: 3306
      DB_USERNAME: root
      DB_PASSWORD: root
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3.8
      - name: Cache Ruby gems
        uses: actions/cache@v4
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: Install dependencies
        run: |
          gem install bundler
          bundle config set --local path vendor/bundle
          bundle install --jobs 4 --retry 3
      - name: Create database configuration
        run: |
          mkdir -p spec/dummy/config
          cat > spec/dummy/config/database.yml << EOF
          default: &default
            adapter: ${DB_ADAPTER}
            encoding: utf8
            pool: 5
            username: ${DB_USERNAME}
            password: ${DB_PASSWORD}
            host: ${DB_HOST}
            port: ${DB_PORT}

          development:
            <<: *default
            database: solidus_development

          test:
            <<: *default
            database: solidus_test

          production:
            <<: *default
            database: solidus_production
          EOF
      - name: Build dummy app
        run: bundle exec rake extension:test_app
      - name: Run tests
        run: bundle exec rake